### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by fia5000** [michelkaeser/docker-pritunl#2]
This is broken, assuming, due to the latest release:

`Traceback (most recent call last):
  File "/usr/bin/pritunl", line 9, in <module>
    load_entry_point('pritunl===1.22.975.2snapshot', 'console_scripts', 'pritunl')()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/__main__.py", line 262, in main
    pritunl.init_server()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/__init__.py", line 18, in init_server
    from pritunl import app
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/app.py", line 7, in <module>
    from pritunl import monitoring
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/monitoring/__init__.py", line 4, in <module>
    from pritunl import influxdb
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/influxdb/__init__.py", line 23, in <module>
    from .client import InfluxDBClient
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/influxdb/client.py", line 37, in <module>
    from .line_protocol import make_lines
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/influxdb/line_protocol.py", line 30, in <module>
    from dateutil.parser import parse`

**Comment by michelkaeser** [comment]
#3 seems to be an indication that the container is working as expected again. Closing this.
